In [5]:
from sklearn.feature_selection import RFE,RFECV
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import numpy as np

In [15]:
from sklearn.linear_model import LogisticRegression

In [4]:
df = pd.read_csv("diabetes.csv")

In [6]:
X = df.drop('Outcome',axis=1)
y = df[['Outcome']]

In [7]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.2,stratify=y)

In [16]:
svc = LogisticRegression()
svc.fit(X,y)

C:\Users\SURUTHI S\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SURUTHI S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
rfe = RFE(svc)

In [18]:
feat = rfe.fit(X,y)

C:\Users\SURUTHI S\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SURUTHI S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\SURUTHI S\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for 

In [19]:
feat.support_

array([ True,  True, False, False, False,  True,  True, False])

In [20]:
feat.ranking_

array([1, 1, 3, 4, 5, 1, 1, 2])

In [21]:
feat.n_features_

4

In [22]:
selected_features = feat.get_support(indices=True)

In [23]:
selected_features

array([0, 1, 5, 6], dtype=int64)